# YOLOv8 Training Configuration
model:
  name: "yolov8n"  # yolov8n, yolov8s, yolov8m, yolov8l, yolov8x
  pretrained: true

# Dataset Configuration
data:
  path: "scripts/data/processed/dataset.yaml"
  train: "scripts/data/processed/train"
  val: "scripts/data/processed/val"
  test: "scripts/data/processed/test"
  
# Class Configuration
classes:
  names:
    0: "pothole"
    1: "garbage_dump"
    2: "waterlogging"
    3: "broken_streetlight"
    4: "damaged_sidewalk"
    5: "construction_debris"
  nc: 6  # number of classes

# Training Parameters
training:
  epochs: 20
  batch_size: 8
  img_size: 640
  patience: 10
  save_period: 5
  
# Optimization
optimizer:
  lr0: 0.01
  momentum: 0.937
  weight_decay: 0.0005

# Augmentation
augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0